// Default strategy configurations.
//
// These are the single source of truth for strategy seeds. They are seeded
// into the database the first time the bot starts and are also used by
// `activeStrategy()` / `strategyById()` to fill in any keys missing from
// older rows so that users on existing databases automatically inherit
// new profitability gates without manual /stratset commands or DB resets.
//
// Custom values previously set by the user always win — only missing keys
// are filled in.

export const COMMON_DEFAULTS = {
  entry_mode: 'immediate',
  min_source_count: 2,
  require_fee_claim: false,
  token_age_max_ms: 0,
  min_mcap_usd: 0,
  max_mcap_usd: 0,
  min_liquidity_usd: 0,
  min_fee_claim_sol: 0,
  min_gmgn_total_fee_sol: 0,
  min_holders: 0,
  max_top20_holder_percent: 100,
  min_saved_wallet_holders: 0,
  max_ath_distance_pct: 0,
  min_graduated_volume_usd: 0,
  trending_min_volume_usd: 0,
  trending_min_swaps: 0,
  trending_max_rug_ratio: 0.3,
  trending_max_bundler_rate: 0.5,
  position_size_sol: 0.1,
  max_open_positions: 3,
  tp_percent: 50,
  sl_percent: -25,
  trailing_enabled: true,
  trailing_percent: 20,
  partial_tp: false,
  partial_tp_at_percent: 0,
  partial_tp_sell_percent: 0,
  max_hold_ms: 0,
  use_llm: true,
  llm_min_confidence: 50,
  // Rug detection: if mcap drops by this percent from its high-water mark
  // after a minimum hold time, exit immediately regardless of trailing state.
  // Set to 0 to disable. Defaults are tuned per-strategy below.
  rug_drop_percent: 45,
  // Wait at least this long after entry before rug-checking, so transient
  // first-fill prints don't trigger false rug exits. Defaults to 60s.
  rug_min_hold_ms: 60_000,
};

export const STRATEGY_DEFAULTS = {
  sniper: {
    ...COMMON_DEFAULTS,
    entry_mode: 'immediate',
    min_source_count: 2,
    require_fee_claim: true,
    token_age_max_ms: 3_600_000,
    min_mcap_usd: 7_000,
    max_mcap_usd: 200_000,
    min_liquidity_usd: 4_000,
    min_fee_claim_sol: 1.0,
    min_gmgn_total_fee_sol: 10,
    min_holders: 50,
    max_top20_holder_percent: 60,
    trending_max_bundler_rate: 0.4,
    position_size_sol: 0.1,
    max_open_positions: 3,
    tp_percent: 60,
    sl_percent: -25,
    trailing_enabled: true,
    trailing_percent: 22,
    partial_tp: true,
    partial_tp_at_percent: 40,
    partial_tp_sell_percent: 40,
    use_llm: true,
    llm_min_confidence: 60,
    rug_drop_percent: 45,
  },
  dip_buy: {
    ...COMMON_DEFAULTS,
    entry_mode: 'wait_for_dip',
    min_source_count: 1,
    require_fee_claim: false,
    token_age_max_ms: 86_400_000,
    min_mcap_usd: 25_000,
    max_mcap_usd: 500_000,
    min_liquidity_usd: 8_000,
    min_holders: 100,
    max_top20_holder_percent: 55,
    max_ath_distance_pct: -40,
    position_size_sol: 0.05,
    max_open_positions: 3,
    tp_percent: 30,
    sl_percent: -20,
    trailing_enabled: true,
    trailing_percent: 15,
    use_llm: true,
    llm_min_confidence: 60,
    rug_drop_percent: 40,
  },
  smart_money: {
    ...COMMON_DEFAULTS,
    entry_mode: 'immediate',
    min_source_count: 2,
    require_fee_claim: false,
    token_age_max_ms: 86_400_000,
    min_mcap_usd: 10_000,
    max_mcap_usd: 1_000_000,
    min_liquidity_usd: 10_000,
    min_holders: 1_500,
    max_top20_holder_percent: 50,
    trending_min_volume_usd: 10_000,
    trending_min_swaps: 150,
    trending_max_rug_ratio: 0.2,
    trending_max_bundler_rate: 0.3,
    position_size_sol: 0.1,
    max_open_positions: 3,
    tp_percent: 100,
    sl_percent: -25,
    trailing_enabled: false,
    trailing_percent: 0,
    partial_tp: true,
    partial_tp_at_percent: 60,
    partial_tp_sell_percent: 40,
    use_llm: true,
    llm_min_confidence: 70,
    rug_drop_percent: 40,
  },
  degen: {
    ...COMMON_DEFAULTS,
    entry_mode: 'immediate',
    min_source_count: 1,
    require_fee_claim: false,
    token_age_max_ms: 3_600_000,
    min_mcap_usd: 7_000,
    max_mcap_usd: 100_000,
    min_liquidity_usd: 3_000,
    min_holders: 50,
    max_top20_holder_percent: 70,
    trending_max_rug_ratio: 0.5,
    trending_max_bundler_rate: 0.5,
    position_size_sol: 0.05,
    max_open_positions: 5,
    tp_percent: 35,
    sl_percent: -18,
    trailing_enabled: true,
    trailing_percent: 12,
    partial_tp: true,
    partial_tp_at_percent: 20,
    partial_tp_sell_percent: 50,
    use_llm: false,
    llm_min_confidence: 0,
    rug_drop_percent: 50,
  },
};

export function strategyConfigWithDefaults(id, stored = {}) {
  const base = STRATEGY_DEFAULTS[id] || COMMON_DEFAULTS;
  return { ...base, ...stored };
}
